describe("Trail", function()
  local trail = require("trail")
  it("should have a direction", function()
    assert.are.equal("", trail.direction(0, 0, 0, 0))
    assert.are.equal("up", trail.direction(0, 0, 0, -1))
    assert.are.equal("down", trail.direction(0, 0, 0, 1))
    assert.are.equal("left", trail.direction(0, 0, -1, 0))
    assert.are.equal("right", trail.direction(0, 0, 1, 0))
  end)
  it("should have a distance", function()
    assert.are.equal("", trail.distance(0, 0, 0, 0))
    assert.are.equal("1 up", trail.distance(0, 0, 0, -1))
    assert.are.equal("1 down", trail.distance(0, 0, 0, 1))
    assert.are.equal(" 1 left", trail.distance(0, 0, -1, 0))
    assert.are.equal(" 1 right", trail.distance(0, 0, 1, 0))
  end)
  it("should route around collisions", function()
    assert.are.equal("Now 0, Up none, Down none, Left none, Right none", trail.route(1, 1, {{0}}))
  end)
  it("should clean a path", function()
    assert.are.same({}, trail.clean_path({}))
  end)
end)
